#!/bin/sh
set -e

if [ "$APIX_ETCD_ENDPOINTS" != "" ]; then
  sed -i "s#- 127.0.0.1:2379#- $APIX_ETCD_ENDPOINTS#g" /go/manager-api/conf/conf.yaml
fi

if [ "$APISIX_CONF_PATH" = "" ]; then
  export APISIX_CONF_PATH="/go/manager-api/conf"
fi

if [ "$ENV" = "" ]; then
  export ENV="prod"
fi

if [ "${1#-}" != "$1" ] || [ "$1" = "" ]; then
  set -- ./manager-api "$@"
fi

exec "$@"
